### ISSUE TITLE
How the covariance matrix is computed using frame level energies in the given code for PriorGrad vocoder

### ISSUE THREAD

**Issue by gashishoo7** [microsoft/NeuralSpeech#102]
Thanks for this great repo. I had gone through the code. I would like to know that in the param.py, what is the difference between condition_prior and condition_prior global? Is the default parameters of param.py file are as given in PriorGrad paper?
And I can see that frame level energies are calculated from the audio spectrogram but how the covariance sigma for normal distribution is calculated? looking forward for your reply. Thanks

**Comment by L0SG** [comment]
Hi, thank you for your interest and sorry for a late reply.

1. condition_prior and condition_prior_global are additional directions we have explored to directly provide the instance-level statistics to the diffusion model itself, rather than formulating it as the prior distribution. Since the paper's focus has been on the latter, these options are set to false as default.

2. PriorGrad assumed diagonal covariance, so a full covariance matrix is not calculated during training and applies [torch.reciprocal](https://github.com/microsoft/NeuralSpeech/blob/3bfa415fa139b88ba4af1d7cbbb8f5f5ba0848f0/PriorGrad-vocoder/learner.py#L57) (an inverse of a diagonal matrix). I'd like to mention that  [a later study](https://arxiv.org/abs/2203.16749) demonstrated a method to estimate the full covariance as an improved way of leveraging the instance-level prior.
