### ISSUE TITLE
Where is the sentencepiece_model?

### ISSUE THREAD

**Issue by Amber921463001** [microsoft/NeuralSpeech#12]
I can‘t find the  sentencepiece_model，can you upload this model if it's convenient for you？ And in eval_aishell.py，I need pass the parameter of  data_name_or_path, I am not sure if I should use train data or dev data or test data.

**Comment by YichongLeng** [comment]
Since our model is a Chinese character-based model, arbitrary SentencePiece model can be used during the inference phase. We provide a SentencePiece model in (https://msramllasc.blob.core.windows.net/modelrelease/FastCorrect_random_sentencepiece.model), which is trained on Chinese wiki data.

The parameter of data_name_or_path should be the path of training binary file. Indeed, the model will only use the dictionary in  data_name_or_path.

**Comment by Amber921463001** [comment]
Thank you for your reply！It helps me a lot！
