### ISSUE TITLE
Fastcorrect2: How to calculate P_{edit}, R_{edit}, P_{right}

### ISSUE THREAD

**Issue by Arrivederci** [microsoft/NeuralSpeech#26]
I completed the experiment with fastcorrect2, it performs well. But I'm not sure how to calculate `P_{edit}, R_{edit}, P_{right}` mentioned in the paper. Could you upload the code?

**Comment by YichongLeng** [comment]
When calculating metrics, we regard the source, FastCorrect2 output and target as _nbest candidate_ and align them with the [align_cal_werdur_v2.py](https://github.com/microsoft/NeuralSpeech/blob/master/FastCorrect2/scripts/align_cal_werdur_v2.py). Since we only need the alignment of source, FastCorrect2 output and target, you can use any text for the _target_ of [align_cal_werdur_v2.py](https://github.com/microsoft/NeuralSpeech/blob/master/FastCorrect2/scripts/align_cal_werdur_v2.py). Once we have the alignment of  source, FastCorrect2 output and target, we can find the errors, errors that are edited, errors that are edited to correct token, based on which we can calculate the metrics.

**Comment by Arrivederci** [comment]
> 

Thank for your answer
