### ISSUE TITLE
Confuses about some parameters

### ISSUE THREAD

**Issue by Chriszhangmw** [microsoft/NeuralSpeech#33]
![image](https://user-images.githubusercontent.com/52879076/167243590-9a303dd5-9618-4b23-b8eb-fe197e82fad1.png)
1): How does the "32768" represents?

2): assert len(tgt_item) == len(for_wer_gather), I got some error about this line on AISHELL-1 dataset, but it still works when I comment on this line, could you help to explain more details about the variable "for_wer_gather"?

**Comment by YichongLeng** [comment]
For the first question, since the data bin requires a non-negative number and there is negative number in duration (standing for error), we add 32768 when generating data bin and subtract 32768 when loading data bin.

For the second question, for_wer_gather is used as index of torch.gather() when constructing decoder input by gathering from encoder input so as to match the decoder input length with the decoder output length. I think the assertion is meaningful and should not be commented out.

**Comment by Chriszhangmw** [comment]
Appreciate your reply. For the second question, there are some length mismatching errors if the assertion is not commented based on the AISHELL-1 dataset as you provided, I am debugging this part and do not fix it out yet, thanks anyway.
